name: Publish Docker image

on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
    env:
      IMAGE_NAME: study-hub-embarque-digital/sth-frontend
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get the latest release tag
        id: get_latest_release
        uses: actions/github-script@v6
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.setOutput('tag', latestRelease.data.tag_name);

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_latest_release.outputs.tag }}
            ${{ secrets.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            VITE_API_BASEURL: ${{ secrets.VITE_API_BASEURL }}
            VITE_API_REFRESH_TOKEN_URL: ${{ secrets.VITE_API_REFRESH_TOKEN_URL }}
            VITE_WS_URL: ${{ secrets.VITE_WS_URL }}
